# Generated by Django 3.2.10 on 2021-12-14 07:13

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time_hours', models.IntegerField()),
                ('time_minutes', models.IntegerField()),
                ('time_seconds', models.IntegerField()),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sport', models.CharField(choices=[('run', 'Run'), ('bike', 'Bike'), ('swim', 'Swim')], default='run', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default='12:00')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('type', models.CharField(choices=[('workout', 'Workout'), ('wu', 'Warm Up'), ('cd', 'Cool Down'), ('race', 'Race')], default='workout', max_length=255)),
                ('effort', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(null=True, upload_to=core.models.recipe_image_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
