# Generated by Django 3.2.10 on 2021-12-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('workout', 'Workout'), ('cd', 'Cool Down'), ('wu', 'Warm Up'), ('race', 'Race')], default='workout', max_length=255),
        ),
    ]
