# Generated by Django 3.2.10 on 2021-12-16 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='effort',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elevation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='My Workout<function now at 0x7f4bf13b8f70>', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('workout', 'Workout'), ('cd', 'Cool Down'), ('wu', 'Warm Up'), ('race', 'Race')], default='workout', max_length=255),
        ),
    ]
